### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by daniep01** [chrishutchinson/train-departure-screen#14]
To help others get this working...
* I suggest adding that the minimum python version is 3.6 due to f"{} {}" notation
* libopenjp2-7 is a requirement and is not included in raspbian stretch lite
  * sudo apt-get install libopenjp2-7

**Comment by chrishutchinson** [comment]
Thanks @daniep01, this is a good shout. I’ll get these notes added later today

**Comment by chrishutchinson** [comment]
All done with the release of [v1.1.2](https://github.com/chrishutchinson/train-departure-screen/releases/tag/v1.1.2)
